### ISSUE TITLE
./install_compiler.py error on Ubuntu 20.04

### ISSUE THREAD

**Issue by xjtuwxg** [ssrg-vt/popcorn-compiler#43]
Envoronment:
```
# cat /etc/issue
Ubuntu 20.04 LTS \n \l
# gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
# g++ --version
g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
```

Error building `llvm`:
```
[ 17%] Building CXX object lib/Transforms/Utils/CMakeFiles/LLVMTransformUtils.dir/CloneFunction.cpp.o
In file included from /usr/local/popcorn/src/llvm/include/llvm/Transforms/Utils/Cloning.h:24,
                 from /usr/local/popcorn/src/llvm/lib/Transforms/Utils/CloneFunction.cpp:16:
/usr/local/popcorn/src/llvm/include/llvm/IR/ValueMap.h: In member function 'bool llvm::ValueMap<KeyT, ValueT, Config>::hasMD() const':
/usr/local/popcorn/src/llvm/include/llvm/IR/ValueMap.h:102:31: error: cannot convert 'const std::unique_ptr<llvm::DenseMap<const llvm::Metadata*, llvm::TrackingMDRef> >' to 'bool' in return
  102 |   bool hasMD() const { return MDMap; }
      |                               ^~~~~
      |                               |
      |                               const std::unique_ptr<llvm::DenseMap<const llvm::Metadata*, llvm::TrackingMDRef> >

```

**Comment by xjtuwxg** [comment]
From this [post](https://github.com/microsoft/DirectXShaderCompiler/issues/1692), this is caused by new C++ standard (g++ 8.1 or newer) specifies operator bool on unique_ptr as being explicit:

```
/usr/local/popcorn/src/llvm/include/llvm/IR/ValueMap.h:102
 bool hasMD() const { return MDMap; }
```
has to be changed to:
```
 bool hasMD() const { return bool(MDMap); }
```
Then go to the llvm build dir and continue the building process:
```
root@ffcdac5850c4:/usr/local/popcorn/src/llvm/build# make -j4
```

**Comment by xjtuwxg** [comment]
This issue can be fixed as mentioned above. However, there are some other libgcc issues when installing libelf. (ubuntu 20.04) `install_compiler.py` works fine on Ubuntu 18.06, 16.04. Close for now. Hope the llvm-9 version is free from this issue.
